name: build

on:
  push:
    paths-ignore:
      - "*.md"
      - "*.pdf"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
      - uses: actions/upload-artifact@v2
        with:
          name: paper
          path: "*.pdf"
      - uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          file_pattern: "*.pdf"
          commit_message: automated PDF build


